services:
  app:
    image: firstapp-prod
    container_name: firstapp-prod
    build:
      context: .
      target: production
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - ENV_FROM_DOCKER_COMPOSE=Environment variable set in docker-compose.yml
